<?php

/**
 * BaseSmsReturn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $return_type
 * @property integer $exit_id
 * @property integer $item_id
 * @property string $return_number
 * @property string $employee_id
 * @property string $store_keeper_id
 * @property integer $quantity
 * @property string $description
 * @property SmsIssue $SmsIssue
 * 
 * @method string    getReturnType()      Returns the current record's "return_type" value
 * @method integer   getExitId()          Returns the current record's "exit_id" value
 * @method integer   getItemId()          Returns the current record's "item_id" value
 * @method string    getReturnNumber()    Returns the current record's "return_number" value
 * @method string    getEmployeeId()      Returns the current record's "employee_id" value
 * @method string    getStoreKeeperId()   Returns the current record's "store_keeper_id" value
 * @method integer   getQuantity()        Returns the current record's "quantity" value
 * @method string    getDescription()     Returns the current record's "description" value
 * @method SmsIssue  getSmsIssue()        Returns the current record's "SmsIssue" value
 * @method SmsReturn setReturnType()      Sets the current record's "return_type" value
 * @method SmsReturn setExitId()          Sets the current record's "exit_id" value
 * @method SmsReturn setItemId()          Sets the current record's "item_id" value
 * @method SmsReturn setReturnNumber()    Sets the current record's "return_number" value
 * @method SmsReturn setEmployeeId()      Sets the current record's "employee_id" value
 * @method SmsReturn setStoreKeeperId()   Sets the current record's "store_keeper_id" value
 * @method SmsReturn setQuantity()        Sets the current record's "quantity" value
 * @method SmsReturn setDescription()     Sets the current record's "description" value
 * @method SmsReturn setSmsIssue()        Sets the current record's "SmsIssue" value
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSmsReturn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sms_return');
        $this->hasColumn('return_type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('exit_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('return_number', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('employee_id', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('store_keeper_id', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('quantity', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SmsIssue', array(
             'local' => 'exit_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}