<?php

/**
 * BaseSmsgroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $group_name
 * @property string $group_code
 * @property string $description
 * @property Doctrine_Collection $SmsItem
 * 
 * @method string              getGroupName()   Returns the current record's "group_name" value
 * @method string              getGroupCode()   Returns the current record's "group_code" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getSmsItem()     Returns the current record's "SmsItem" collection
 * @method Smsgroup            setGroupName()   Sets the current record's "group_name" value
 * @method Smsgroup            setGroupCode()   Sets the current record's "group_code" value
 * @method Smsgroup            setDescription() Sets the current record's "description" value
 * @method Smsgroup            setSmsItem()     Sets the current record's "SmsItem" collection
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSmsgroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('smsgroup');
        $this->hasColumn('group_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('group_code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SmsItem', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}