<?php

/**
 * BaseSmsCustomerOrganization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $customer_id
 * @property string $customer_organization_tin_number
 * @property string $customer_oraganization_name
 * @property string $customer_oraganization_acronym
 * @property string $customer_oraganization_head_office_name
 * @property string $customer_oraganization_head_office_phone
 * @property string $customer_oraganization_chief_executive_name
 * @property string $customer_oraganization_contact_person
 * @property string $customer_oraganization_designation
 * @property string $customer_oraganization_place
 * @property string $customer_oraganization_email
 * @property string $customer_oraganization_phone_number
 * @property string $customer_oraganization_fax
 * @property string $customer_oraganization_web_site
 * @property string $customer_oraganization_global_head_count
 * @property string $customer_oraganization_local_head_count
 * @property date $customer_oraganization_founded_date
 * @property string $ownership
 * 
 * @method string                  getCustomerId()                                  Returns the current record's "customer_id" value
 * @method string                  getCustomerOrganizationTinNumber()               Returns the current record's "customer_organization_tin_number" value
 * @method string                  getCustomerOraganizationName()                   Returns the current record's "customer_oraganization_name" value
 * @method string                  getCustomerOraganizationAcronym()                Returns the current record's "customer_oraganization_acronym" value
 * @method string                  getCustomerOraganizationHeadOfficeName()         Returns the current record's "customer_oraganization_head_office_name" value
 * @method string                  getCustomerOraganizationHeadOfficePhone()        Returns the current record's "customer_oraganization_head_office_phone" value
 * @method string                  getCustomerOraganizationChiefExecutiveName()     Returns the current record's "customer_oraganization_chief_executive_name" value
 * @method string                  getCustomerOraganizationContactPerson()          Returns the current record's "customer_oraganization_contact_person" value
 * @method string                  getCustomerOraganizationDesignation()            Returns the current record's "customer_oraganization_designation" value
 * @method string                  getCustomerOraganizationPlace()                  Returns the current record's "customer_oraganization_place" value
 * @method string                  getCustomerOraganizationEmail()                  Returns the current record's "customer_oraganization_email" value
 * @method string                  getCustomerOraganizationPhoneNumber()            Returns the current record's "customer_oraganization_phone_number" value
 * @method string                  getCustomerOraganizationFax()                    Returns the current record's "customer_oraganization_fax" value
 * @method string                  getCustomerOraganizationWebSite()                Returns the current record's "customer_oraganization_web_site" value
 * @method string                  getCustomerOraganizationGlobalHeadCount()        Returns the current record's "customer_oraganization_global_head_count" value
 * @method string                  getCustomerOraganizationLocalHeadCount()         Returns the current record's "customer_oraganization_local_head_count" value
 * @method date                    getCustomerOraganizationFoundedDate()            Returns the current record's "customer_oraganization_founded_date" value
 * @method string                  getOwnership()                                   Returns the current record's "ownership" value
 * @method SmsCustomerOrganization setCustomerId()                                  Sets the current record's "customer_id" value
 * @method SmsCustomerOrganization setCustomerOrganizationTinNumber()               Sets the current record's "customer_organization_tin_number" value
 * @method SmsCustomerOrganization setCustomerOraganizationName()                   Sets the current record's "customer_oraganization_name" value
 * @method SmsCustomerOrganization setCustomerOraganizationAcronym()                Sets the current record's "customer_oraganization_acronym" value
 * @method SmsCustomerOrganization setCustomerOraganizationHeadOfficeName()         Sets the current record's "customer_oraganization_head_office_name" value
 * @method SmsCustomerOrganization setCustomerOraganizationHeadOfficePhone()        Sets the current record's "customer_oraganization_head_office_phone" value
 * @method SmsCustomerOrganization setCustomerOraganizationChiefExecutiveName()     Sets the current record's "customer_oraganization_chief_executive_name" value
 * @method SmsCustomerOrganization setCustomerOraganizationContactPerson()          Sets the current record's "customer_oraganization_contact_person" value
 * @method SmsCustomerOrganization setCustomerOraganizationDesignation()            Sets the current record's "customer_oraganization_designation" value
 * @method SmsCustomerOrganization setCustomerOraganizationPlace()                  Sets the current record's "customer_oraganization_place" value
 * @method SmsCustomerOrganization setCustomerOraganizationEmail()                  Sets the current record's "customer_oraganization_email" value
 * @method SmsCustomerOrganization setCustomerOraganizationPhoneNumber()            Sets the current record's "customer_oraganization_phone_number" value
 * @method SmsCustomerOrganization setCustomerOraganizationFax()                    Sets the current record's "customer_oraganization_fax" value
 * @method SmsCustomerOrganization setCustomerOraganizationWebSite()                Sets the current record's "customer_oraganization_web_site" value
 * @method SmsCustomerOrganization setCustomerOraganizationGlobalHeadCount()        Sets the current record's "customer_oraganization_global_head_count" value
 * @method SmsCustomerOrganization setCustomerOraganizationLocalHeadCount()         Sets the current record's "customer_oraganization_local_head_count" value
 * @method SmsCustomerOrganization setCustomerOraganizationFoundedDate()            Sets the current record's "customer_oraganization_founded_date" value
 * @method SmsCustomerOrganization setOwnership()                                   Sets the current record's "ownership" value
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSmsCustomerOrganization extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sms_customer_organization');
        $this->hasColumn('customer_id', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('customer_organization_tin_number', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_acronym', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_head_office_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_head_office_phone', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_chief_executive_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_contact_person', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_designation', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_place', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_email', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_phone_number', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_fax', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_web_site', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_global_head_count', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_local_head_count', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('customer_oraganization_founded_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ownership', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}