<?php

/**
 * SmsCustomerOrganizationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsCustomerOrganizationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsCustomerOrganizationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SmsCustomerOrganization');
    }
}