<?php

/**
 * SmsfamilyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsfamilyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsfamilyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Smsfamily');
    }
}