<?php

/**
 * SmsFamilyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsFamilyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsFamilyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SmsFamily');
    }
}