<?php

/**
 * SmsgroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsgroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsgroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Smsgroup');
    }
}