<?php

/**
 * SmsIssueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsIssueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsIssueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SmsIssue');
    }
}