<?php

/**
 * SmsItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SmsItem');
    }
}