<?php

/**
 * SmsRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SmsRequest');
    }
}