<?php

/**
 * SmsReturnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsReturnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsReturnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SmsReturn');
    }
}