<?php

/**
 * SmsStockRecieptTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsStockRecieptTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsStockRecieptTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SmsStockReciept');
    }
}