<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/11/12 17:35:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sms',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
